project: 
  type: website

execute: 
  freeze: auto

website: 
  title: "Penguin Model Website"
  navbar: 
    left: 
      - href: index.qmd
        text: Home
      - href: eda-basic.qmd
        text: EDA
      - href: model-py.qmd
        text: Model

format: 
  html: 
    theme: cosmo 
    toc: true