project: 
  type: website

website: 
  title: "Penguin Model Website"
  navbar: 
    left: 
      - href: index.qmd
        text: Home
      - href: eda.qmd
        text: EDA
      - href: model.qmd
        text: Model

format: 
  html: 
    theme: cosmo 
    toc: true